### ISSUE TITLE
Not Working 

### ISSUE THREAD

**Issue by WaterKnight1998** [Tinkoff/deimos#2]
Good afternoon,

I have tried to use deimos to convert XSD into Case Classes but I can't get it working.

Is there any alternative? I have seen this script referenced on phobos doc

**Comment by valentiay** [comment]
Hi!

Does #3 fix the problem? Deimos may not work in some complex cases. If you provide some examples of errors, I will try to make deimos support them.

As far as I know, there are no other scripts, which could convert XSD to phobos classes

**Comment by WaterKnight1998** [comment]
Hi @valentiay, yes, I solved the issue thank you very much :)
